### ISSUE TITLE
Once you RLogin no more telnet

### ISSUE THREAD

**Issue by GaryAiles** [rickparrish/TelnetDoor#1]
Hi, I have net2bbs spawning telnet door.  There are 5 servers in the config, 4 are telnet and TW2002 is Rlogin.  Once you've Rlogin to TW, after exiting selecting any other server will fail "doesn't accept Rlogin connection" (or similar).     Can be seen at (http or telnet) web.bbsgametime.com .  Thanks.

**Comment by DesotoFireflite** [comment]
Gary, as far as I remember,  you can't have both telnet and rogin in the same config file, or the program crashes. You will need to run two config files like I do on Valhalla. Rick might have a work around by now however. 

⁣Get BlueMail for Android ​

**Comment by rickparrish** [comment]
This was a stupid mistake on my part -- I should have been resetting the app settings between each connection attempt.  By not resetting them, making an rlogin connection set the "is this an rlogin connection flag", and there was no way to reset that flag, so all subsequent telnet connections were treated as rlogin connections too.

I've updated things so a reset now happens before each connection, so this should be fixed.  It took me longer than expected to fix it because the new Visual Studio doesn't support the old framework I was using before, so I didn't have time to actually test it out.  Hopefully it works, but please back up your old version just in case it doesn't.  And I'll take a closer look later tonight if it needs further fixing.

And since the framework version had to change to 4.6.2 (the oldest VS 2022 supports), you may need to install that version of the framework on your computer before it'll run.

**Comment by DesotoFireflite** [comment]
Awesome,  thanks Rick. It didn't really bother me, as I figured a work around years ago, but I'll switch to the newer version in a few days. Thanks for all your hard work.

⁣Get BlueMail for Android ​

**Comment by GaryAiles** [comment]
Wow!  Thank you!
